services:
  odontopro:
    image: postgres:latest
    container_name: odontopro
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: odontopro
    restart: always
